export const datasource = [
  {
    id: 1,
    name: "A",
    content: "ssssssssssssssssss",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 2,
    name: "C",
    content: "eeeeeeeeeeeeeeee",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 3,
    name: "B",
    content: "eeeeeeeeeeeeeeee",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 4,
    name: "D",
    content: "ssssssssssssssssss",
    date: "12.9.2021",
    status: "closed",
  },
  {
    id: 5,
    name: "E",
    content: "eeeeeeeeeeeeeeee",
    date: "30.9.2021",
    status: "open",
  },
  {
    id: 6,
    name: "F",
    content: "eeeeeeeeeeeeeeee",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 7,
    name: "G",
    content: "ssssssssssssssssss",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 8,
    name: "H",
    content: "eeeeeeeeeeeeeeee",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 9,
    name: "I",
    content: "eeeeeeeeeeeeeeee",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 10,
    name: "J",
    content: "ssssssssssssssssss",
    date: "12.9.2021",
    status: "closed",
  },
  {
    id: 11,
    name: "K",
    content: "eeeeeeeeeeeeeeee",
    date: "30.9.2021",
    status: "open",
  },
  {
    id: 12,
    name: "L",
    content: "eeeeeeeeeeeeeeee",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 13,
    name: "M",
    content: "ssssssssssssssssss",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 14,
    name: "N",
    content: "eeeeeeeeeeeeeeee",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 15,
    name: "O",
    content: "eeeeeeeeeeeeeeee",
    date: "30.9.2021",
    status: "closed",
  },
  {
    id: 16,
    name: "P",
    content: "ssssssssssssssssss",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 17,
    name: "R",
    content: "eeeeeeeeeeeeeeee",
    date: "30.9.2021",
    status: "open",
  },
  {
    id: 18,
    name: "S",
    content: "eeeeeeeeeeeeeeee",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 19,
    name: "T",
    content: "ssssssssssssssssss",
    date: "12.9.2021",
    status: "closed",
  },
  {
    id: 20,
    name: "U",
    content: "eeeeeeeeeeeeeeee",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 21,
    name: "V",
    content: "eeeeeeeeeeeeeeee",
    date: "12.9.2021",
    status: "open",
  },
  {
    id: 22,
    name: "Z",
    content: "ssssssssssssssssss",
    date: "12.9.2021",
    status: "open",
  },
];
